[package]
name = "opentale_inventory"
version = "0.2.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.13.0" }
bevy-inspector-egui = "0.31.0"